version: "3"
services:
  wa-services:
    build:
      context: .
      dockerfile: dockerfile
    image: "fikridulumina/wa-services:tatest"
    container_name: wa-services
    volumes:
      - "./:/app/"
    ports:
      - 8000:8000
